### ISSUE TITLE
能添加个折叠吗，看着更舒服

### ISSUE THREAD

**Issue by fentianx** [springtwr/siyuan-code-tabs#5]
能折叠代码，保留标题

**Comment by springtwr** [comment]
> 能折叠代码，保留标题

目前不打算添加该特性到插件里面，思源本身可以折叠所有的块，将鼠标放到块左上角的悬浮按钮上时可以看到折叠和展开块的操作方式。你的需求可以用css片段来实现，通过`设置 -> 外观 -> 代码片段 -> 设置`添加css片段即可。以下是一个可用的示例片段，可根据你的需求调整其中的参数：
```css
.protyle-wysiwyg [data-node-id][data-type="NodeHTMLBlock"][custom-plugin-code-tabs-sourcecode][fold="1"]{
    opacity: 1!important; /* 设置折叠后的透明度 */
    height: 3em!important; /* 设置折叠后的高度 */
}
```
此issue将暂时关闭，后续有问题再重新打开。
